version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=wearthe_user
      - POSTGRES_PASSWORD=development_password
      - POSTGRES_DB=wearthe_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wearthe_user -d wearthe_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    environment:
      - REDIS_HOST=localhost
      - REDIS_PASSWORD=passwrod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
